services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"